[project]
name = "uqcs-hackathon-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "blessed>=1.48.0",
    "numpy>=2.5.2",
]

[tool.ruff]
line-length = 160

[tool.ruff.lint]
extend-select = ["I"]

[dependency-groups]
dev = [
    "basedpyright>=1.39.10",
    "mypy>=2.3.1",
    "ruff>=0.16.4",
]

[tool.mypy]
python_version = "3.12"
strict = true
